### ISSUE TITLE
Add GitHub Action

### ISSUE THREAD

**Issue by jefftriplett** [revsys/vinnie#18]
Instead of having to install vinnie, it'd be nice to make Vinnie a proper GitHub action so that it's quick and easy to run natively: 

```yaml
    - uses: revsys/vinnie@v1
      with:
        ...
```
